version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"
      
volumes:
  postgres-data:
